<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\domainevent\\eventenvelopetest' => '/EventEnvelopeTest.php',
                'spriebsch\\domainevent\\nullabletest' => '/stubs/TestEvent.php',
                'spriebsch\\domainevent\\serializationtest' => '/SerializationTest.php',
                'spriebsch\\domainevent\\somebackedenum' => '/stubs/TestEvent.php',
                'spriebsch\\domainevent\\someenum' => '/stubs/TestEvent.php',
                'spriebsch\\domainevent\\somevalueobject' => '/stubs/TestEvent.php',
                'spriebsch\\domainevent\\testevent' => '/stubs/TestEvent.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
