<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\domainevent\\abstractidtest' => '/AbstractIdTest.php',
                'spriebsch\\domainevent\\complexevent' => '/doubles/ComplexEvent.php',
                'spriebsch\\domainevent\\envelopeerrortest' => '/EnvelopeErrorTest.php',
                'spriebsch\\domainevent\\eventa' => '/doubles/EventA.php',
                'spriebsch\\domainevent\\eventb' => '/doubles/EventB.php',
                'spriebsch\\domainevent\\eventc' => '/doubles/EventC.php',
                'spriebsch\\domainevent\\eventenvelopetest' => '/EventEnvelopeTest.php',
                'spriebsch\\domainevent\\eventwithoutcorrelationid' => '/doubles/EventWithoutCorrelationId.php',
                'spriebsch\\domainevent\\eventwithouttopic' => '/doubles/EventWithoutTopic.php',
                'spriebsch\\domainevent\\eventwithtwocorrelationids' => '/doubles/EventWithTwoCorrelationIds.php',
                'spriebsch\\domainevent\\generatetopicmaptest' => '/GenerateTopicMapTest.php',
                'spriebsch\\domainevent\\nestedvalueobject' => '/doubles/NestedValueObject.php',
                'spriebsch\\domainevent\\nullable' => '/doubles/Nullable.php',
                'spriebsch\\domainevent\\payloadtest' => '/PayloadTest.php',
                'spriebsch\\domainevent\\serializationtest' => '/SerializationTest.php',
                'spriebsch\\domainevent\\simpleevent' => '/doubles/SimpleEvent.php',
                'spriebsch\\domainevent\\somebackedenum' => '/doubles/SomeBackedEnum.php',
                'spriebsch\\domainevent\\someenum' => '/doubles/SomeEnum.php',
                'spriebsch\\domainevent\\somevalueobject' => '/doubles/SomeValueObject.php',
                'spriebsch\\domainevent\\testevent' => '/doubles/TestEvent.php',
                'spriebsch\\domainevent\\testid' => '/doubles/TestId.php',
                'spriebsch\\domainevent\\topictest' => '/TopicTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
