<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\domainevent\\complexevent' => '/stubs/ComplexEvent.php',
                'spriebsch\\domainevent\\domaineventtest' => '/DomainEventTest.php',
                'spriebsch\\domainevent\\eventa' => '/stubs/EventA.php',
                'spriebsch\\domainevent\\eventb' => '/stubs/EventB.php',
                'spriebsch\\domainevent\\eventc' => '/stubs/EventC.php',
                'spriebsch\\domainevent\\eventenvelopetest' => '/EventEnvelopeTest.php',
                'spriebsch\\domainevent\\eventwithoutcorrelationid' => '/stubs/EventWithoutCorrelationId.php',
                'spriebsch\\domainevent\\nullabletest' => '/stubs/ComplexEvent.php',
                'spriebsch\\domainevent\\serializationtest' => '/SerializationTest.php',
                'spriebsch\\domainevent\\simpleevent' => '/stubs/SimpleEvent.php',
                'spriebsch\\domainevent\\somebackedenum' => '/stubs/ComplexEvent.php',
                'spriebsch\\domainevent\\someenum' => '/stubs/ComplexEvent.php',
                'spriebsch\\domainevent\\somevalueobject' => '/stubs/ComplexEvent.php',
                'spriebsch\\domainevent\\testevent' => '/stubs/TestEvent.php',
                'spriebsch\\domainevent\\testid' => '/stubs/TestId.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
