<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\domainevent\\abstractid' => '/ids/AbstractId.php',
                'spriebsch\\domainevent\\causationid' => '/ids/CausationId.php',
                'spriebsch\\domainevent\\correlationid' => '/ids/CorrelationId.php',
                'spriebsch\\domainevent\\domainevent' => '/DomainEvent.php',
                'spriebsch\\domainevent\\domaineventdeserializer' => '/DomainEventDeserializer.php',
                'spriebsch\\domainevent\\domaineventserializer' => '/DomainEventSerializer.php',
                'spriebsch\\domainevent\\envelope' => '/Envelope.php',
                'spriebsch\\domainevent\\eventid' => '/ids/EventId.php',
                'spriebsch\\domainevent\\eventtopic' => '/topic/EventTopic.php',
                'spriebsch\\domainevent\\jsondomaineventdeserializer' => '/json/JsonDomainEventDeserializer.php',
                'spriebsch\\domainevent\\jsondomaineventserializer' => '/json/JsonDomainEventSerializer.php',
                'spriebsch\\domainevent\\maptotopic' => '/attributes/MapToTopic.php',
                'spriebsch\\domainevent\\payload' => '/Payload.php',
                'spriebsch\\domainevent\\schemaversion' => '/SchemaVersion.php',
                'spriebsch\\domainevent\\topicmap' => '/topic/TopicMap.php',
                'spriebsch\\domainevent\\useascorrelationid' => '/attributes/UseAsCorrelationId.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
